name: agricultural-dev

services:
  agricultural-minio:
    image: minio/minio:latest
    container_name: agricultural-minio
    ports:
      - "9900:9900"
      - "9901:9901"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    networks: [appnet]

  agricultural-mongodb:
    image: mongo:8.0
    container_name: agricultural-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: Asia/Bangkok
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand({ ping: 1 }).ok",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    networks: [appnet]

volumes:
  mongo_data:
  minio_data:

networks:
  appnet:
    driver: bridge
