<?php

declare(strict_types=1);

return [
  'home' => [
    'title' => 'พื้นที่การเกษตรให้เช่า',
    'view'  => 'home',
    'css'   => ['pages/home.css'],
    'js'    => ['pages/home.js'],
  ],
  'signin' => [
    'title'      => 'เข้าสู่ระบบ',
    'view'       => 'signin',
    'css'        => ['pages/signin.css'],
    'js'         => ['pages/signin.js'],
    'guest_only' => true,
  ],
  'signup' => [
    'title'      => 'สมัครสมาชิก',
    'view'       => 'signup',
    'css'        => ['pages/signup.css'],
    'js'         => ['pages/signup.js'],
    'guest_only' => true,
  ],
  'profile' => [
    'title' => 'โปรไฟล์สมาชิกเกษตร',
    'view'  => 'profile',
    'css'   => ['pages/profile.css'],
    'js'    => ['pages/profile.js'],
    'auth'  => true,
  ],
  'detail' => [
    'title' => 'รายละเอียดแปลงเกษตร',
    'view'  => 'detail',
    'css'   => ['pages/detail.css'],
    'js'    => ['pages/detail.js'],
  ],
  'payment' => [
    'title' => 'ชำระมัดจำเช่าพื้นที่เกษตร',
    'view'  => 'payment',
    'css'   => ['pages/payment.css'],
    'js'    => ['pages/payment.js'],
    'auth'  => true,
  ],
  'full_payment' => [
    'title' => 'ชำระเงินเต็มจำนวน',
    'view'  => 'full_payment',
    'css'   => ['pages/full_payment.css'],
    'js'    => ['pages/full_payment.js'],
    'auth'  => true,
  ],
  'history' => [
    'title' => 'ประวัติการเช่าพื้นที่เกษตร',
    'view'  => 'history',
    'css'   => ['pages/history.css'],
    'js'    => ['pages/history.js'],
    'auth'  => true,
  ],
  'my_properties' => [
    'title' => 'พื้นที่ปล่อยเช่าของฉัน',
    'view'  => 'my_properties',
    'css'   => ['pages/my_properties.css'],
    'js'    => ['pages/my_properties.js', 'features/property-images.js'],
    'auth'  => true,
  ],
  'property_bookings' => [
    'title' => 'รายการจองพื้นที่',
    'view'  => 'property_bookings',
    'css'   => ['pages/property_bookings.css'],
    'js'    => ['pages/property_bookings.js'],
    'auth'  => true,
  ],
  'add_property' => [
    'title' => 'เพิ่มพื้นที่ปล่อยเช่า',
    'view'  => 'add_property',
    'css'   => ['pages/add_property.css'],
    'js'    => ['pages/add_property.js'],
    'auth'  => true,
  ],
  'edit_property' => [
    'title' => 'แก้ไขพื้นที่ปล่อยเช่า',
    'view'  => 'edit_property',
    'css'   => ['pages/add_property.css'],
    'js'    => ['pages/edit_property.js'],
    'auth'  => true,
  ],
  'delete_property' => [
    'title' => 'ลบพื้นที่',
    'view'  => 'delete_property',
    'js'    => ['pages/delete_property.js'],
    'auth'  => true,
  ],
  'delete_property_image' => [
    'title' => 'ลบรูปภาพ',
    'view'  => 'delete_property_image',
    'js'    => ['features/property-images.js'],
    'auth'  => true,
  ],
  'admin_dashboard' => [
    'title' => 'แดชบอร์ดผู้ดูแลระบบ',
    'view'  => 'admin_dashboard',
    'css'   => ['pages/admin_dashboard.css'],
    'js'    => ['pages/admin_dashboard.js'],
    'auth'  => true,
    'admin' => true,
  ],
  'payment_verification' => [
    'title' => 'ตรวจสอบการชำระเงิน',
    'view'  => 'payment_verification',
    'css'   => ['pages/admin_dashboard.css'],
    'js'    => ['pages/payment_verification.js'],
    'auth'  => true,
    'admin' => true,
  ],
  'reports' => [
    'title' => 'รายงานและสถิติ',
    'view'  => 'reports',
    'css'   => ['pages/admin_dashboard.css'],
    'js'    => ['pages/reports.js'],
    'auth'  => true,
    'admin' => true,
  ],
  'advanced_search' => [
    'title' => 'ค้นหาขั้นสูง',
    'view'  => 'advanced_search',
    'css'   => [],
    'js'    => ['pages/advanced_search.js'],
  ],
  'view_contract' => [
    'title' => 'ดูสัญญา',
    'view'  => 'view_contract',
    'css'   => ['pages/contract.css'],
    'js'    => ['pages/view_contract.js'],
    'auth'  => true,
  ],
];
